export const resources = [
  {
    title: 'Lead generation for freelancers',
    href: '/resources/lead-generation-for-freelancers',
    description: 'How freelancers can find better-fit clients without relying only on referrals.',
    lastModified: '2026-04-01',
  },
  {
    title: 'Lead generation for agencies',
    href: '/resources/lead-generation-for-agencies',
    description: 'How agencies can build a steadier client pipeline with better prospecting.',
    lastModified: '2026-04-01',
  },
  {
    title: 'How to find business leads',
    href: '/resources/how-to-find-business-leads',
    description: 'A practical guide to finding business leads more consistently and efficiently.',
    lastModified: '2026-04-01',
  },
  {
    title: 'Find local business leads',
    href: '/resources/find-local-business-leads',
    description: 'How to find businesses in a target city or region without wasting time manually.',
    lastModified: '2026-04-01',
  },
  {
    title: 'B2B lead generation',
    href: '/resources/b2b-lead-generation',
    description: 'A clearer way to think about B2B targeting, pipeline quality, and consistency.',
    lastModified: '2026-04-01',
  },
  {
    title: 'Cold outreach for lead generation',
    href: '/resources/cold-outreach-for-lead-generation',
    description: 'Why targeting matters more than messaging in cold outreach performance.',
    lastModified: '2026-04-01',
  },
  {
    title: 'Lead generation tools',
    href: '/resources/lead-generation-tools',
    description: 'How to evaluate lead generation tools based on workflow, speed, and relevance.',
    lastModified: '2026-04-01',
  },
  {
    title: 'How to qualify leads',
    href: '/resources/how-to-qualify-leads',
    description: 'How to filter out poor-fit prospects before outreach or sales time is wasted.',
    lastModified: '2026-04-01',
  },
  {
    title: 'How to build a lead generation system',
    href: '/resources/lead-generation-system',
    description: 'A framework for turning lead generation from random effort into a repeatable process.',
    lastModified: '2026-04-01',
  },
  {
    title: 'Cost of lead generation',
    href: '/resources/cost-of-lead-generation',
    description: 'Why the time cost of finding leads is often more expensive than the tool cost.',
    lastModified: '2026-04-01',
  },
  {
    title: 'Manual vs lead generation tools',
    href: '/resources/manual-vs-lead-generation-tools',
    description: 'A direct comparison of manual prospecting and tools across time, cost, and consistency.',
    lastModified: '2026-04-01',
  },
  {
    title: 'Best lead generation tools',
    href: '/resources/best-lead-generation-tools',
    description: 'A balanced guide to lead generation tool categories, tradeoffs, and fit.',
    lastModified: '2026-04-01',
  },
  {
    title: 'How many leads do you need?',
    href: '/resources/how-many-leads-do-you-need',
    description: 'A practical way to connect lead volume, conversion rate, and predictable revenue.',
    lastModified: '2026-04-01',
  },
  {
    title: 'ALPA vs Apollo',
    href: '/resources/alpa-vs-apollo',
    description: 'A neutral comparison of ALPA and Apollo based on workflow, speed, and prospecting fit.',
    lastModified: '2026-04-15',
  },
]
